[package]
name = "rs_gb_desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.16.0"
eframe = "0.33"
bytemuck = "1.24"
ringbuf = "0.4.8"
rfd = "0.16"
rs_gb_core = { path = "../rsGB-core" }